# .github/workflows/release.yml
name: Release (beta on main, prod on release)

on:
  push:
    branches: [main, release]
  workflow_dispatch:

permissions:
  contents: write

concurrency:
  group: release-${{ github.ref }}
  cancel-in-progress: true

jobs:
  plan:
    runs-on: ubuntu-latest
    outputs:
      next_tag: ${{ steps.plan.outputs.new_tag }}
      prerelease: ${{ steps.pre.outputs.prerelease }}
    steps:
      - uses: actions/checkout@v4
      - id: plan
        uses: mathieudutour/github-tag-action@v6.2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          pre_release_branches: main
          release_branches: release
          append_to_pre_release_tag: beta
          default_prerelease_bump: preminor
          dry_run: true
      - id: pre
        run: |
          [[ "${{ steps.plan.outputs.new_tag }}" == *"-beta."* ]] && v=true || v=false
          echo "prerelease=$v" >> "$GITHUB_OUTPUT"

  build:
    needs: plan
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - uses: docker/build-push-action@v5
        with:
          context: .
          push: false
          cache-from: type=gha
          cache-to: type=gha,mode=max
      # place optional container smoke tests here

  finalize:
    needs: [plan, build]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - id: tag
        uses: mathieudutour/github-tag-action@v6.2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          pre_release_branches: main
          release_branches: release
          append_to_pre_release_tag: beta
          default_prerelease_bump: preminor
          tag_prefix: "" # ← no leading "v"

      - name: Assert planned vs actual tag
        run: test "${{ steps.tag.outputs.new_tag }}" = "${{ needs.plan.outputs.next_tag }}"

      - uses: ncipollo/release-action@v1
        with:
          tag: ${{ steps.tag.outputs.new_tag }}
          name: Release ${{ steps.tag.outputs.new_tag }}
          body: ${{ steps.tag.outputs.changelog }}
          prerelease: ${{ needs.plan.outputs.prerelease }}

      - uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - uses: docker/setup-buildx-action@v3
      - uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          cache-from: type=gha
          cache-to: type=gha,mode=max
          tags: |
            russellotniel/personal-repository:${{ steps.tag.outputs.new_tag }}
            ${{ contains(steps.tag.outputs.new_tag, '-beta.') && 'russellotniel/personal-repository:latest-beta' || 'russellotniel/personal-repository:latest' }}
